name: Package Addon

on:
  push:
    tags: ["*"]
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Jayrgo/luacheck-action@0.1.0
  build:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Validate Package
        run: ./ci.sh
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GH_TOKEN }}
      - name: Create Package
        run: ./ci.sh RELEASE-THE-HOUNDS
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GH_TOKEN }}
